apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::271093570830:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MNKL3BS5YIZG
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::271093570830:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-03T22:46:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "927"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f5e740e2-0429-4460-8c0a-bfd22a9ececd
